version: '2.3'
services:
  infra-worker:
    build:
      context: infra-worker
      dockerfile: Dockerfile
    container_name: infra-worker
    volumes:
      - ./infra-worker:/go/src/app
    ports:
      - "4000:4000" # For debugger
    depends_on:
    - mongodb
    - postgres
    - chart-museum
    networks:
      - default

  postgres:
    image: postgres:15.1-alpine3.17
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
     - ./data/mount:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  #https://chartmuseum.com/docs/
  chart-museum:
    image: bitnami/chartmuseum:0.15.0-debian-11-r79
    container_name: chart-museum
    entrypoint: chartmuseum
    user: "0"
    command:
        - --port=8080
        - --storage=local
        - --storage-local-rootdir=/charts
        - --basic-auth-user=athmos
        - --basic-auth-pass=athmos
    ports:
      - "8080:8080"
  init-chart-museum:
    build:
      context: docker-images/helm
      dockerfile: Dockerfile
    container_name: init-chart-museum
    user: "0"
    entrypoint: "/charts/package.sh true"
    working_dir: /charts
    environment:
      REPOSITORY_USERNAME: "athmos"
      REPOSITORY_PASSWORD: "athmos"
      REPOSITORY_ADDRESS: "chart-museum:8080"

    depends_on:
      - chart-museum
    volumes:
      - ./plugins/infra/crossplane:/charts
networks:
 default:
  driver: bridge